### ISSUE TITLE
unable to change user

### ISSUE THREAD

**Issue by jranita** [frePPLe/frepple#193]
ERROR Internal Server Error: /data/common/user/2/change/
Traceback (most recent call last):
  File "C:\develop\Python35\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\develop\Python35\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\develop\Python35\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\develop\Python35\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\develop\Python35\lib\site-packages\django\contrib\admin\options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\develop\Python35\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\develop\Python35\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\develop\Python35\lib\site-packages\django\contrib\admin\sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "C:\develop\Python35\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\develop\Python35\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\develop\Python35\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\develop\Python35\lib\contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "C:\Users\frePPLe\Documents\frePPLe_comunity\contrib\django\freppledb\common\adminforms.py", line 442, in change_view
    return super().change_view(request, object_id, form_url, new_extra_context)
  File "C:\develop\Python35\lib\site-packages\django\contrib\admin\options.py", line 1511, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\develop\Python35\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\develop\Python35\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\develop\Python35\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\develop\Python35\lib\site-packages\django\contrib\admin\options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\develop\Python35\lib\site-packages\django\contrib\admin\options.py", line 1448, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "C:\Users\frePPLe\Documents\frePPLe_comunity\contrib\django\freppledb\common\adminforms.py", line 99, in save_model
    obj.save(using=request.database)
  File "C:\Users\frePPLe\Documents\frePPLe_comunity\contrib\django\freppledb\common\models.py", line 417, in save
    update_fields=update_fields
  File "C:\develop\Python35\lib\site-packages\django\contrib\auth\base_user.py", line 80, in save
    super(AbstractBaseUser, self).save(*args, **kwargs)
  File "C:\develop\Python35\lib\site-packages\django\db\models\base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\develop\Python35\lib\site-packages\django\db\models\base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\develop\Python35\lib\site-packages\django\db\models\base.py", line 903, in _save_table
    forced_update)
  File "C:\develop\Python35\lib\site-packages\django\db\models\base.py", line 933, in _do_update
    filtered = base_qs.filter(pk=pk_val)
  File "C:\develop\Python35\lib\site-packages\django\db\models\query.py", line 781, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\develop\Python35\lib\site-packages\django\db\models\query.py", line 799, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\develop\Python35\lib\site-packages\django\db\models\sql\query.py", line 1260, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\develop\Python35\lib\site-packages\django\db\models\sql\query.py", line 1286, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "C:\develop\Python35\lib\site-packages\django\db\models\sql\query.py", line 1220, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\develop\Python35\lib\site-packages\django\db\models\sql\query.py", line 1114, in build_lookup
    return final_lookup(lhs, rhs)
  File "C:\develop\Python35\lib\site-packages\django\db\models\lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\develop\Python35\lib\site-packages\django\db\models\lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\develop\Python35\lib\site-packages\django\db\models\fields\__init__.py", line 962, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'change'

**Comment by jdetaeye** [comment]
Must have been introduced with migration to django 1.11

I suspect the root cause to be here, which is an override to a standard django function:
File "C:\develop\Python35\lib\site-packages\django\contrib\admin\options.py", line 1408, in changeform_view
return self._changeform_view(request, object_id, form_url, extra_context)

**Comment by jdetaeye** [comment]
Ran into this at Newell as well. Looked a bit into it, and it's a pretty nasty one...

**Comment by jranita** [comment]
Tested OK.
