### ISSUE TITLE
Error creating initial database under ubuntu 18.04

### ISSUE THREAD

**Issue by andreltr** [frePPLe/frepple#300]
Hello,

I'm receiving a lot of error messages when installing frepple under ubuntu 18.04.  The messages are below.  All the previous steps were accomplished without errors.

Note from 2018-09-07 17:45:47.353

sudo frepplectl migrate --noinput
Traceback (most recent call last):
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection  self.connect()
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect  self.connection = self.get_new_connection(conn_params)
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection  connection = Database.connect(**conn_params)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 130, in connect   conn = _connect(dsn, connection_factory=connection_factory, **kwasync) psycopg2.OperationalError: FATAL:  Peer authentication failed for user "frepple"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/frepplectl", line 39, in <module>
    execute_from_command_line(sys.argv)
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line utility.execute()
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv  self.execute(*args, **cmd_options)
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute  output = self.handle(*args, **options)
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 83, in handle  executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 20, in __init__  self.loader = MigrationLoader(self.connection)
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 52, in __init__  self.build_graph()
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 209, in build_graph  self.applied_migrations = recorder.applied_migrations()
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 65, in applied_migrations  self.ensure_schema()
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 52, in ensure_schema  if self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor()):
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 254, in cursor  return self._cursor()
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 229, in _cursor  self.ensure_connection()
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection  self.connect()
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__   six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise  raise value.with_traceback(tb)
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection  self.connect()
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect   self.connection = self.get_new_connection(conn_params)
  File "/home/andreltr/.local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection   connection = Database.connect(**conn_params)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 130, in connect  conn = _connect(dsn, connection_factory=connection_factory, **kwasync) django.db.utils.OperationalError: FATAL:  Peer authentication failed for user "frepple"

Any help highly appreciated.

Thanks,

Andre Luiz

**Comment by andreltr** [comment]
i didn't realize and knew that! Please accept my apologies.  The mailing list will be used from now on.
