### ISSUE TITLE
DETAIL:  Key (name)=(xxx) is still referenced from table "calendarbucket".

### ISSUE THREAD

**Issue by robinhli** [frePPLe/frepple#343]
when read the odoo data 2nd time, frepple first delete the previous odoo data, but it first delete the calendar, then delete the calendar bucket. 

I think it should be first delete calendar bucket, then delete the calendar, correct?

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\LHB\Company\DTraining\dsaps\freppledb\common\commands.py", line 549, in <module>
    register.run(database=database)
  File "D:\LHB\Company\DTraining\dsaps\freppledb\common\commands.py", line 487, in run
    cls.reg.run(**cls.arguments)
  File "D:\LHB\Company\DTraining\dsaps\freppledb\common\commands.py", line 220, in run
    step.run(**PlanTaskRegistry.getArguments())
  File "D:\LHB\Company\DTraining\dsaps\freppledb\input\commands\export.py", line 178, in run
    (source, cls.timestamp),
  File "D:\Python35\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "D:\Python35\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Python35\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Python35\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Python35\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: update or delete on table "calendar" violates foreign key constraint "calendarbucket_calendar_id_19d343fa_fk_calendar_name" on table "calendarbucket"
DETAIL:  Key (name)=(xxx) is still referenced from table "calendarbucket".

Error: Error executing Python command

**Comment by jdetaeye** [comment]
Fixed
