### ISSUE TITLE
Error when importing setup matrices and rules from Odoo

### ISSUE THREAD

**Issue by kunesj** [frePPLe/frepple#351]
Happened after I improved export from Odoo to also return "setup matrices" and "setup matrix rules". 
Errors were logged after executing "Create Plan - Read Odoo data". 
I am 100% sure it's not bug in my code, but in frePPLe.

```
INFO Start step 305 'Export static data' at 09:15:33
INFO Start step exportstatic1 1 'Export setup matrix rules' at 09:15:33
INFO Start step exportstatic2 1 'Export customers' at 09:15:33
INFO Start step exportstatic3 1 'Export calendar buckets' at 09:15:33
INFO Start step exportstatic4 1 'Export buffers' at 09:15:33
ERROR Exception caught on thread exportstatic1
INFO Finished 'Export buffers' at 09:15:33 
INFO Start step exportstatic4 2 'Export operation material' at 09:15:33
Error during planning: 'frepple.setupmatrixrule_default' object has no attribute 'source'
INFO Finished 'Export calendar buckets' at 09:15:33 
INFO Finished 'Export operation material' at 09:15:33 
INFO Start step exportstatic4 3 'Export suppliers' at 09:15:33
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/freppledb/common/commands.py", line 547, in <module>
    register.run(database=database)
  File "/usr/local/lib/python3.6/dist-packages/freppledb/common/commands.py", line 487, in run
    cls.reg.run(**cls.arguments)
  File "/usr/local/lib/python3.6/dist-packages/freppledb/common/commands.py", line 220, in run
    step.run(**PlanTaskRegistry.getArguments())
  File "/usr/local/lib/python3.6/dist-packages/freppledb/common/commands.py", line 334, in run
    raise t.exception
  File "/usr/local/lib/python3.6/dist-packages/freppledb/common/commands.py", line 297, in run
    self.seq.run(**self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/freppledb/common/commands.py", line 220, in run
    step.run(**PlanTaskRegistry.getArguments())
  File "/usr/local/lib/python3.6/dist-packages/freppledb/input/commands/export.py", line 727, in run
    getData(),
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 1198, in execute_batch
INFO Finished 'Export suppliers' at 09:15:33 
INFO Start step exportstatic4 4 'Export item suppliers' at 09:15:33
INFO Finished 'Export item suppliers' at 09:15:33 
INFO Start step exportstatic4 5 'Export item distributions' at 09:15:33
INFO Finished 'Export item distributions' at 09:15:33 
INFO Finished 'Export customers' at 09:15:33 
INFO Start step exportstatic2 2 'Export sales orders' at 09:15:33
    for page in _paginate(argslist, page_size=page_size):
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 1169, in _paginate
    page.append(next(it))
  File "/usr/local/lib/python3.6/dist-packages/freppledb/input/commands/export.py", line 692, in getData
    if source and source != i.source:
AttributeError: 'frepple.setupmatrixrule_default' object has no attribute 'source'
Error: Error executing Python command
```
And another one after fixing the one before:
```
INFO Start step 305 'Export static data' at 09:17:00
INFO Start step exportstatic1 1 'Export setup matrix rules' at 09:17:00
INFO Start step exportstatic2 1 'Export customers' at 09:17:00
INFO Start step exportstatic3 1 'Export calendar buckets' at 09:17:00
INFO Start step exportstatic4 1 'Export buffers' at 09:17:00
ERROR Exception caught on thread exportstatic1
INFO Finished 'Export buffers' at 09:17:00 
INFO Start step exportstatic4 2 'Export operation material' at 09:17:00
Error during planning: column "matrix_id" does not exist
LINE 4:                 on conflict (matrix_id, priority)
                                    ^

INFO Finished 'Export calendar buckets' at 09:17:00 
INFO Finished 'Export customers' at 09:17:00 
INFO Start step exportstatic2 2 'Export sales orders' at 09:17:00
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: column "matrix_id" does not exist
LINE 4:                 on conflict (matrix_id, priority)
                                    ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
INFO Finished 'Export operation material' at 09:17:00 
INFO Start step exportstatic4 3 'Export suppliers' at 09:17:00
  File "/usr/local/lib/python3.6/dist-packages/freppledb/common/commands.py", line 547, in <module>
    register.run(database=database)
  File "/usr/local/lib/python3.6/dist-packages/freppledb/common/commands.py", line 487, in run
    cls.reg.run(**cls.arguments)
  File "/usr/local/lib/python3.6/dist-packages/freppledb/common/commands.py", line 220, in run
    step.run(**PlanTaskRegistry.getArguments())
  File "/usr/local/lib/python3.6/dist-packages/freppledb/common/commands.py", line 334, in run
    raise t.exception
  File "/usr/local/lib/python3.6/dist-packages/freppledb/common/commands.py", line 297, in run
    self.seq.run(**self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/freppledb/common/commands.py", line 220, in run
    step.run(**PlanTaskRegistry.getArguments())
  File "/usr/local/lib/python3.6/dist-packages/freppledb/input/commands/export.py", line 727, in run
    getData(),
  File "/usr/lib/python3/dist-packages/psycopg2/extras.py", line 1200, in execute_batch
    cur.execute(b";".join(sqls))
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
INFO Finished 'Export sales orders' at 09:17:00 
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: column "matrix_id" does not exist
LINE 4:                 on conflict (matrix_id, priority)
                                    ^

Error: Error executing Python command
```

I was able to fix it with following changes, but I am pretty sure that's not correct way to do it (setup rule using source value from setup matrix), and I don't understand frePPLe enough to fix this properly.

```
---------------------- freppledb/input/commands/export.py ----------------------
index e391b1fd2..26281f3b0 100644
@@ -689,7 +689,7 @@ class exportSetupRules(PlanTask):
         def getData():
             for m in frepple.setupmatrices():
                 for i in m.rules:
-                    if source and source != i.source:
+                    if source and source != m.source:
                         continue
                     r = [
                         m.name,
@@ -699,7 +699,7 @@ class exportSetupRules(PlanTask):
                         i.duration,
                         round(i.cost, 8),
                         i.resource.name if i.resource else None,
-                        i.source,
+                        m.source,
                         cls.timestamp,
                     ]
                     for a in attrs:
@@ -712,7 +712,7 @@ class exportSetupRules(PlanTask):
                 """insert into setuprule
                 (setupmatrix_id,priority,fromsetup,tosetup,duration,cost,resource_id,source,lastmodified%s)
                 values(%%s,%%s,%%s,%%s,%%s * interval '1 second',%%s,%%s,%%s,%%s%s)
-                on conflict (matrix_id, priority)
+                on conflict (setupmatrix_id, priority)
                 do update set
                   fromsetup=excluded.fromsetup,
                   tosetup=excluded.tosetup,
```

**Comment by jdetaeye** [comment]
The errors were on frepple side.  Fixed with 701ba30458030abcba2bc603c4aff436718b0ebe 
Thanks for reporting!
