### ISSUE TITLE
deletion of suboperation in operation form fails

### ISSUE THREAD

**Issue by jdetaeye** [frePPLe/frepple#357]
Reproduce:
1) https://demo.frepple.com/detail/input/operation/Varnish%20chair/ open edit form of an operation that has suboperations
2) select the "delete" checkbox for one of the suboperations
3) Save.    This will results in a error 500 error 

Analysis:
Stack trace in web server:
```
[Fri May 29 06:40:43.456927 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488] ERROR Internal Server Error: /detail/input/operation/Varnish chair/
[Fri May 29 06:40:43.456967 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488] Traceback (most recent call last):
[Fri May 29 06:40:43.456972 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
[Fri May 29 06:40:43.456977 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     response = get_response(request)
[Fri May 29 06:40:43.456981 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
[Fri May 29 06:40:43.456986 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     response = self.process_exception_by_middleware(e, request)
[Fri May 29 06:40:43.456991 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
[Fri May 29 06:40:43.456996 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri May 29 06:40:43.457000 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
[Fri May 29 06:40:43.457013 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     return view_func(request, *args, **kwargs)
[Fri May 29 06:40:43.457017 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/lib/python3/dist-packages/freppledb/common/views.py", line 532, in detail
[Fri May 29 06:40:43.457021 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     return newtab["viewfunc"](request, object_id)
[Fri May 29 06:40:43.457025 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py", line 606, in wrapper
[Fri May 29 06:40:43.457029 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     return self.admin_site.admin_view(view)(*args, **kwargs)
[Fri May 29 06:40:43.457033 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
[Fri May 29 06:40:43.457036 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     response = view_func(request, *args, **kwargs)
[Fri May 29 06:40:43.457040 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
[Fri May 29 06:40:43.457044 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     response = view_func(request, *args, **kwargs)
[Fri May 29 06:40:43.457048 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/sites.py", line 223, in inner
[Fri May 29 06:40:43.457052 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     return view(request, *args, **kwargs)
[Fri May 29 06:40:43.457055 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 45, in _wrapper
[Fri May 29 06:40:43.457059 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     return bound_method(*args, **kwargs)
[Fri May 29 06:40:43.457063 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
[Fri May 29 06:40:43.457067 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     response = view_func(request, *args, **kwargs)
[Fri May 29 06:40:43.457071 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/lib/python3.6/contextlib.py", line 52, in inner
[Fri May 29 06:40:43.457074 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     return func(*args, **kwds)
[Fri May 29 06:40:43.457078 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/lib/python3/dist-packages/freppledb/common/adminforms.py", line 433, in change_view
[Fri May 29 06:40:43.457082 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     return super().change_view(request, object_id, form_url, new_extra_context)
[Fri May 29 06:40:43.457086 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py", line 1648, in change_view
[Fri May 29 06:40:43.457090 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     return self.changeform_view(request, object_id, form_url, extra_context)
[Fri May 29 06:40:43.457093 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 45, in _wrapper
[Fri May 29 06:40:43.457101 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     return bound_method(*args, **kwargs)
[Fri May 29 06:40:43.457105 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
[Fri May 29 06:40:43.457108 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     response = view_func(request, *args, **kwargs)
[Fri May 29 06:40:43.457112 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py", line 1529, in changeform_view
[Fri May 29 06:40:43.457116 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     return self._changeform_view(request, object_id, form_url, extra_context)
[Fri May 29 06:40:43.457120 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py", line 1574, in _changeform_view
[Fri May 29 06:40:43.457124 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     change_message = self.construct_change_message(request, form, formsets, add)
[Fri May 29 06:40:43.457128 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py", line 1050, in construct_change_message
[Fri May 29 06:40:43.457131 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     return construct_change_message(form, formsets, add)
[Fri May 29 06:40:43.457135 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]   File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/utils.py", line 520, in construct_change_message
[Fri May 29 06:40:43.457139 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488]     'object': str(deleted_object),
[Fri May 29 06:40:43.457145 2020] [wsgi:error] [pid 25073:tid 140682561074944] [remote 95.182.208.70:7488] TypeError: __str__ returned non-string (type NoneType)
```

Workaround: 
Delete record from the operation grid

**Comment by jdetaeye** [comment]
Bug has been fixed since.  And the form has changed as well.
