### ISSUE TITLE
Server error (500) when clicking on Admin - Execute

### ISSUE THREAD

**Issue by snelstim** [frePPLe/frepple#411]
Everything seems to be working okay, but when I click on admin - execute I get server error (500)
the text mentions Oops, something went wrong.
Your administrator can find more information on the error in the log file /var/log/apache2/error.log

I checked the logfile mentioned but there is nothing in there.
I'm using the latest docker container 6.17.1 on Ubuntu 20.04.2 LTS

**Comment by snelstim** [comment]
I found some information in the logs:

[Thu Oct 21 14:36:25.045210 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782] Traceback (most recent call last):
[Thu Oct 21 14:36:25.045232 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
[Thu Oct 21 14:36:25.045244 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     response = get_response(request)
[Thu Oct 21 14:36:25.045255 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
[Thu Oct 21 14:36:25.045267 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     response = self.process_exception_by_middleware(e, request)
[Thu Oct 21 14:36:25.045278 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
[Thu Oct 21 14:36:25.045289 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Thu Oct 21 14:36:25.045300 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 71, in view
[Thu Oct 21 14:36:25.045311 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.dispatch(request, *args, **kwargs)
[Thu Oct 21 14:36:25.045322 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 45, in _wrapper
[Thu Oct 21 14:36:25.045333 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return bound_method(*args, **kwargs)
[Thu Oct 21 14:36:25.045343 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
[Thu Oct 21 14:36:25.045354 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return view_func(request, *args, **kwargs)
[Thu Oct 21 14:36:25.045365 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 45, in _wrapper
[Thu Oct 21 14:36:25.045393 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return bound_method(*args, **kwargs)
[Thu Oct 21 14:36:25.045405 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
[Thu Oct 21 14:36:25.045415 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     response = view_func(request, *args, **kwargs)
[Thu Oct 21 14:36:25.045425 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/lib/python3/dist-packages/freppledb/common/report.py", line 853, in dispatch
[Thu Oct 21 14:36:25.045435 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.get(request, *args_unquoted, **kwargs)
[Thu Oct 21 14:36:25.045445 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/lib/python3/dist-packages/freppledb/common/report.py", line 1776, in get
[Thu Oct 21 14:36:25.045455 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return render(request, cls.template, context)
[Thu Oct 21 14:36:25.045465 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/shortcuts.py", line 36, in render
[Thu Oct 21 14:36:25.045475 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     content = loader.render_to_string(template_name, context, request, using=using)
[Thu Oct 21 14:36:25.045485 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/loader.py", line 62, in render_to_string
[Thu Oct 21 14:36:25.045495 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return template.render(context, request)
[Thu Oct 21 14:36:25.045504 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/backends/django.py", line 61, in render
[Thu Oct 21 14:36:25.045514 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.template.render(context)
[Thu Oct 21 14:36:25.045524 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 171, in render
[Thu Oct 21 14:36:25.045534 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self._render(context)
[Thu Oct 21 14:36:25.045544 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 163, in _render
[Thu Oct 21 14:36:25.045554 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.nodelist.render(context)
[Thu Oct 21 14:36:25.045563 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
[Thu Oct 21 14:36:25.045573 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     bit = node.render_annotated(context)
[Thu Oct 21 14:36:25.045583 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
[Thu Oct 21 14:36:25.045593 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.render(context)
[Thu Oct 21 14:36:25.045602 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/loader_tags.py", line 150, in render
[Thu Oct 21 14:36:25.045612 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return compiled_parent._render(context)
[Thu Oct 21 14:36:25.045622 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 163, in _render
[Thu Oct 21 14:36:25.045640 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.nodelist.render(context)
[Thu Oct 21 14:36:25.045651 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
[Thu Oct 21 14:36:25.045661 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     bit = node.render_annotated(context)
[Thu Oct 21 14:36:25.045671 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
[Thu Oct 21 14:36:25.045681 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.render(context)
[Thu Oct 21 14:36:25.045690 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/loader_tags.py", line 150, in render
[Thu Oct 21 14:36:25.045700 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return compiled_parent._render(context)
[Thu Oct 21 14:36:25.045710 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 163, in _render
[Thu Oct 21 14:36:25.045720 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.nodelist.render(context)
[Thu Oct 21 14:36:25.045730 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
[Thu Oct 21 14:36:25.045739 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     bit = node.render_annotated(context)
[Thu Oct 21 14:36:25.045749 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
[Thu Oct 21 14:36:25.045759 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.render(context)
[Thu Oct 21 14:36:25.045769 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/loader_tags.py", line 150, in render
[Thu Oct 21 14:36:25.045779 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return compiled_parent._render(context)
[Thu Oct 21 14:36:25.045788 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 163, in _render
[Thu Oct 21 14:36:25.045798 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.nodelist.render(context)
[Thu Oct 21 14:36:25.045808 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
[Thu Oct 21 14:36:25.045818 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     bit = node.render_annotated(context)
[Thu Oct 21 14:36:25.045828 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
[Thu Oct 21 14:36:25.045837 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.render(context)
[Thu Oct 21 14:36:25.045847 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/loader_tags.py", line 150, in render
[Thu Oct 21 14:36:25.045857 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return compiled_parent._render(context)
[Thu Oct 21 14:36:25.045867 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 163, in _render
[Thu Oct 21 14:36:25.045885 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.nodelist.render(context)
[Thu Oct 21 14:36:25.045895 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
[Thu Oct 21 14:36:25.045905 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     bit = node.render_annotated(context)
[Thu Oct 21 14:36:25.045915 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
[Thu Oct 21 14:36:25.045925 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.render(context)
[Thu Oct 21 14:36:25.045935 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/loader_tags.py", line 62, in render
[Thu Oct 21 14:36:25.045945 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     result = block.nodelist.render(context)
[Thu Oct 21 14:36:25.045955 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
[Thu Oct 21 14:36:25.045965 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     bit = node.render_annotated(context)
[Thu Oct 21 14:36:25.045975 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
[Thu Oct 21 14:36:25.045985 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.render(context)
[Thu Oct 21 14:36:25.045994 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/loader_tags.py", line 62, in render
[Thu Oct 21 14:36:25.046004 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     result = block.nodelist.render(context)
[Thu Oct 21 14:36:25.046014 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
[Thu Oct 21 14:36:25.046024 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     bit = node.render_annotated(context)
[Thu Oct 21 14:36:25.046033 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
[Thu Oct 21 14:36:25.046043 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.render(context)
[Thu Oct 21 14:36:25.046053 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/defaulttags.py", line 309, in render
[Thu Oct 21 14:36:25.046063 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return nodelist.render(context)
[Thu Oct 21 14:36:25.046073 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
[Thu Oct 21 14:36:25.046083 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     bit = node.render_annotated(context)
[Thu Oct 21 14:36:25.046093 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
[Thu Oct 21 14:36:25.046103 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.render(context)
[Thu Oct 21 14:36:25.046112 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/defaulttags.py", line 209, in render
[Thu Oct 21 14:36:25.046132 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     nodelist.append(node.render_annotated(context))
[Thu Oct 21 14:36:25.046143 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
[Thu Oct 21 14:36:25.046153 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return self.render(context)
[Thu Oct 21 14:36:25.046163 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/local/lib/python3.6/dist-packages/django/template/library.py", line 192, in render
[Thu Oct 21 14:36:25.046173 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     output = self.func(*resolved_args, **resolved_kwargs)
[Thu Oct 21 14:36:25.046183 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/lib/python3/dist-packages/freppledb/common/templatetags.py", line 746, in call_method
[Thu Oct 21 14:36:25.046193 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     return method(*args) if method else None
[Thu Oct 21 14:36:25.046203 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]   File "/usr/lib/python3/dist-packages/freppledb/execute/management/commands/scenario_copy.py", line 437, in getHTML
[Thu Oct 21 14:36:25.046213 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782]     for f in sorted(os.listdir(settings.FREPPLE_LOGDIR)):
[Thu Oct 21 14:36:25.046227 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782] FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/logs'
[Thu Oct 21 14:36:25.046247 2021] [wsgi:error] [pid 24:tid 140679289284352] [remote 192.168.5.4:1782] 
 
anyone knows what could be the problem? created a clean install of ubuntu and still the same issue
