### ISSUE TITLE
Beta2.2 -  'Settings' object has no attribute 'DEFAULT_DASHBOARD'

### ISSUE THREAD

**Issue by jbradsha** [frePPLe/frePPLe#48]
Error after logging in as admin on fresh build of Beta2.2 downloaded 2014-12-02
(Built with ./configure --disable-lp_solver)

Environment:
Ubuntu 14.04.1 LTS
64-bit

Request Method: GET
Request URL: http://localhost:8000/admin/

Django Version: 1.6
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.admin',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'freppledb.input',
 'freppledb.output',
 'freppledb.execute',
 'freppledb.common')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'freppledb.common.middleware.LocaleMiddleware',
 'freppledb.common.middleware.DatabaseSelectionMiddleware',
 'django.middleware.common.CommonMiddleware')

$ frepplectl runserver
Validating models...

0 errors found
December 02, 2014 - 18:33:31
Django version 1.6, using settings 'freppledb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[02/Dec/2014 18:33:41] "GET / HTTP/1.1" 301 0
[02/Dec/2014 18:33:41] "GET /admin/ HTTP/1.1" 200 3208
[02/Dec/2014 18:33:41] "GET /data/jsi18n/ HTTP/1.1" 200 3220
[02/Dec/2014 18:33:41] "GET /static/css/sunny/jquery-ui.min.css HTTP/1.1" 200 27045
[02/Dec/2014 18:33:41] "GET /static/js/jquery-ui-1.10.4.min.js HTTP/1.1" 200 228539
[02/Dec/2014 18:33:41] "GET /static/js/i18n/jquery.ui.datepicker-en.js HTTP/1.1" 200 874
[02/Dec/2014 18:33:41] "GET /static/css/font-awesome.min.css HTTP/1.1" 200 20766
[02/Dec/2014 18:33:41] "GET /static/js/jquery-1.11.0.min.js HTTP/1.1" 200 96381
[02/Dec/2014 18:33:41] "GET /static/js/i18n/grid.locale-en.js HTTP/1.1" 200 6612
[02/Dec/2014 18:33:41] "GET /static/img/frepple.svg HTTP/1.1" 200 6009
[02/Dec/2014 18:33:41] "GET /static/css/ui.jqgrid.css HTTP/1.1" 200 12642
[02/Dec/2014 18:33:41] "GET /static/css/frepple.css HTTP/1.1" 200 9065
[02/Dec/2014 18:33:41] "GET /static/js/jquery.jqGrid.min.js HTTP/1.1" 200 260457
[02/Dec/2014 18:33:41] "GET /static/js/frepple.js HTTP/1.1" 200 55503
[02/Dec/2014 18:33:41] "GET /static/favicon.ico HTTP/1.1" 200 36220
[02/Dec/2014 18:33:45] "POST /admin/ HTTP/1.1" 302 0
ERROR Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 139, in get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/lib/python2.7/dist-packages/freppledb/common/templatetags/base_utils.py", line 406, in render
    context[self.varname] = [ {'width': i['width'], 'widgets': [ reg[j[0]](**j[1]) for j in i['widgets'] if reg[j[0]].has_permission(req.user)]} for i in settings.DEFAULT_DASHBOARD ]
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'DEFAULT_DASHBOARD'

**Comment by jdetaeye** [comment]
Closing the issue as the dashboard has been completely revamped & reworked in the recent versions.
